### ISSUE TITLE
Can't update using PPA? Ubuntu 11.04 (64-bit)

### ISSUE THREAD

**Issue by lukearmstrong** [bjori/php5-vanilla-ubuntu#2]
I found your ppa:bjori/php5 and your blog, so I thought I would give it a go on my computer and my linode. Both are running Ubuntu 11.04 (64-bit).

I already have php5 installed from the ubuntu repository, as I am currently using Nginx and PHP5 FPM, so I hoped I could just upgrade to your version without any messing around. I like that you have built using MySQLnd, the bundled GD, and without Suhosin.

$> sudo add-apt-repository ppa:bjori/php5
$> sudo apt-get update
$> sudo apt-get upgrade
= Nothing to upgrade?

Running "sudo apt-cache show php5" doesn't list your release of php5.3.6, just the normal ubuntu php5.3.5

I'm using PPAs for the latest stable releases of Git, Mercurial and Nginx without any issues.

I'm guessing this PPA isn't working for me because I am running the 64-bit version of ubuntu?

**Comment by bjori** [comment]
On Sun, Jul 3, 2011 at 13:16, lukearmstrong
reply@reply.github.com
wrote:

> I found your ppa:bjori/php5 and your blog, so I thought I would give it a go on my computer and my linode. Both are running Ubuntu 11.04 (64-bit).
> 
> [...]
> 
> I'm guessing this PPA isn't working for me because I am running the 64-bit version of ubuntu?

Yeahh.. I'm having some issues with Natty as they have changed lot of
libraries - and removed some 64bit ones it looks like.
I'm looking into these issues and hope to have it fixed in the next few days.

-Hannes

**Comment by philip** [comment]
Also, this bug report will be a great base for Issue #1. :)
